# Generated by Django 4.0.4 on 2022-04-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recongition', '0002_face_rename_recongitions_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='img',
            field=models.ImageField(upload_to='temp/'),
        ),
    ]
